from ..language import component as component
from ..matcher import Matcher as Matcher
from ..util import filter_spans as filter_spans
from typing import Any

def merge_noun_chunks(doc: Any): ...
def merge_entities(doc: Any): ...
def merge_subtokens(doc: Any, label: str = ...): ...
