from .. import about as about
from ..util import get_package_path as get_package_path
from .link import link as link
from typing import Any, Optional

def download(model: Any, direct: bool = ..., *pip_args: Any) -> None: ...
def require_package(name: Any): ...
def get_json(url: Any, desc: Any): ...
def get_compatibility(): ...
def get_version(model: Any, comp: Any): ...
def download_model(filename: Any, user_pip_args: Optional[Any] = ...): ...
