from ..util import load_model as load_model
from typing import Any, Optional

def profile(model: Any, inputs: Optional[Any] = ..., n_texts: int = ...) -> None: ...
def parse_texts(nlp: Any, texts: Any) -> None: ...
