from typing import Any, Optional

class DocBin:
    attrs: Any = ...
    tokens: Any = ...
    spaces: Any = ...
    cats: Any = ...
    user_data: Any = ...
    strings: Any = ...
    store_user_data: Any = ...
    def __init__(self, attrs: Optional[Any] = ..., store_user_data: bool = ...) -> None: ...
    def __len__(self): ...
    def add(self, doc: Any) -> None: ...
    def get_docs(self, vocab: Any) -> None: ...
    def merge(self, other: Any) -> None: ...
    def to_bytes(self): ...
    def from_bytes(self, bytes_data: Any): ...
Binder = DocBin
