from typing import Iterator

from .span import Span
from .token import Token

class Doc:
    @overload
    def __getitem__(self, i: int) -> Token: ...
    @overload
    def __getitem__(self, i: slice) -> Span: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Token]: ...
