from ...gold import iob_to_biluo as iob_to_biluo
from ...lang.xx import MultiLanguage as MultiLanguage
from ...tokens.doc import Doc as Doc
from ...util import load_model as load_model
from typing import Any, Optional

def conll_ner2json(input_data: Any, n_sents: int = ..., seg_sents: bool = ..., model: Optional[Any] = ..., no_print: bool = ..., **kwargs: Any): ...
def segment_sents_and_docs(doc: Any, n_sents: Any, doc_delimiter: Any, model: Optional[Any] = ..., msg: Optional[Any] = ...): ...
def segment_docs(input_data: Any, n_sents: Any, doc_delimiter: Any): ...
def n_sents_info(msg: Any, n_sents: Any) -> None: ...
