from ...gold import iob_to_biluo as iob_to_biluo
from ...util import minibatch as minibatch
from .conll_ner2json import n_sents_info as n_sents_info
from typing import Any

def iob2json(input_data: Any, n_sents: int = ..., no_print: bool = ..., *args: Any, **kwargs: Any): ...
def read_iob(raw_sents: Any): ...
def merge_sentences(docs: Any, n_sents: Any): ...
