from ..attrs import ID as ID, NORM as NORM, ORTH as ORTH, PREFIX as PREFIX, SHAPE as SHAPE, SUFFIX as SUFFIX
from typing import Any

def Tok2Vec(width: Any, embed_size: Any, **kwargs: Any): ...
def flatten(seqs: Any, drop: float = ...): ...
def concatenate_lists(*layers: Any, **kwargs: Any): ...
