from ..util import make_layer as make_layer, registry as registry
from ._wire import concatenate_lists as concatenate_lists
from typing import Any

def Tok2Vec(config: Any): ...
def Doc2Feats(config: Any): ...
def MultiHashEmbed(config: Any): ...
def CharacterEmbed(config: Any): ...
def MaxoutWindowEncoder(config: Any): ...
def MishWindowEncoder(config: Any): ...
def PretrainedVectors(config: Any): ...
def TorchBiLSTMEncoder(config: Any): ...
