from .errors import Errors as Errors, Warnings as Warnings, user_warning as user_warning
from .tokens import Doc as Doc, Span as Span, Token as Token
from typing import Any

def analyze_pipes(pipeline: Any, name: Any, pipe: Any, index: Any, warn: bool = ...): ...
def analyze_all_pipes(pipeline: Any, warn: bool = ...): ...
def dot_to_dict(values: Any): ...
def validate_attrs(values: Any): ...
def get_assigns_for_attr(pipeline: Any, attr: Any): ...
def get_requires_for_attr(pipeline: Any, attr: Any): ...
def print_summary(nlp: Any, pretty: bool = ..., no_print: bool = ...): ...
