from .render import DependencyRenderer as DependencyRenderer, EntityRenderer as EntityRenderer
from typing import Any, Optional

RENDER_WRAPPER: Any

def render(docs: Any, style: str = ..., page: bool = ..., minify: bool = ..., jupyter: Optional[Any] = ..., options: Any = ..., manual: bool = ...): ...
def serve(docs: Any, style: str = ..., page: bool = ..., minify: bool = ..., options: Any = ..., manual: bool = ..., port: int = ..., host: str = ...) -> None: ...
def app(environ: Any, start_response: Any): ...
def parse_deps(orig_doc: Any, options: Any = ...): ...
def parse_ents(doc: Any, options: Any = ...): ...
def set_render_wrapper(func: Any) -> None: ...
def get_doc_settings(doc: Any): ...
